name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: ./Backend
      
    - name: Run tests
      run: npm test
      working-directory: ./Backend
